export const training = [
  {
    type: '胸',
    menuNames: [
      { name: 'プッシュアップ', subtext: '腕立て伏せです' },
      {
        name: 'ヒンドゥープッシュアップ',
        subtext: '尻を上げた後、腰の横まで前方移動する腕立て伏せです',
      },
      {
        name: 'リバースプッシュアップ',
        subtext: '背面の腕立て伏せです',
      },
      {
        name: 'ナロープッシュアップ',
        subtext: '両手の幅を狭めた腕立て伏せです',
      },
      {
        name: 'ワイドプッシュアップ',
        subtext: '両手の幅を広げた腕立て伏せです',
      },
      { name: 'オルタネートプッシュアップ', subtext: '手の位置を左右非対称にして行う腕立て伏せです' },
      {
        name: 'クロスプッシュアップ',
        subtext: '膝を立て、腕を交差して行う腕立て伏せです',
      },
      {
        name: '片手プッシュアップ',
        subtext: '片手を背中につけ、もう一方のみで行う腕立て伏せです',
      },
      {
        name: 'トライアングルプッシュアップ',
        subtext: '親指と人差し指で三角形を作った状態で行う腕立て伏せです',
      },
    ],
  },
  {
    type: '肩',
    menuNames: [
      { name: '壁プッシュアップ', subtext: '' },
      { name: 'バーティカルプッシュアップ', subtext: '' },
      { name: 'ショルダー・サイドシットアップ', subtext: '' },
      { name: 'サジタルプッシュアップ', subtext: '' },
      { name: '逆立ちプレス', subtext: '' },
      { name: 'セルフレジスタンス・デルトイドローイング', subtext: '' },
      { name: 'マニュアルレジスタンス・アップライトロー', subtext: '' },
      { name: 'マニュアルレジスタンス・サイドレイズ', subtext: '' },
      { name: 'マニュアルレジスタンス・リアレイズ', subtext: '' },
    ],
  },
  {
    type: '腕',
    menuNames: [
      { name: 'テーブルアームカール', subtext: '' },
      { name: 'セルフレジスタンス・エルボーエクステンション', subtext: '' },
      { name: 'エルボーエクステンション', subtext: '' },
      { name: '壁ダイヤモンドプッシュアップ', subtext: '' },
      { name: 'ダイヤモンドプッシュアップ', subtext: '' },
      { name: 'マニュアルレジスタンス・アームカール', subtext: '' },
      { name: 'マニュアルレジスタンス・エルボーエクステンション', subtext: '' },
    ],
  },
  {
    type: '上背',
    menuNames: [
      { name: 'テーブル・エルボープルアップ', subtext: '' },
      {
        name: 'テーブル・インバーテッドローイング（アンダーグリップ）',
        subtext: '',
      },
      { name: 'テーブル・インバーテッドローイング（オーバーグリップ）', subtext: '' },
      { name: 'シュラッグ', subtext: '' },
      {
        name: 'マニュアルレジスタンス・ワンハンドローイング（ベントオーバー）',
      },
      {
        name: 'マニュアルレジスタンス・ワンハンドローイング（アップライト）',
        subtext: '',
      },
    ],
  },
  {
    type: '首',
    menuNames: [
      { name: 'ネックフレクション', subtext: '' },
      { name: 'サイドネックフレクション', subtext: '' },
      { name: 'フロントブリッジフレクション', subtext: '' },
      { name: 'フロントブリッジツイスト', subtext: '' },
      { name: 'バックブリッジフレクション', subtext: '' },
      { name: 'セルフレジスタンス・サイドネックフレクション', subtext: '' },
      { name: 'セルフレジスタンス・ネックフレクション①', subtext: '' },
      { name: 'セルフレジスタンス・ネックフレクション②', subtext: '' },
      { name: 'マニュアルレジスタンス・ネックフレクション', subtext: '' },
      { name: 'マニュアルレジスタンス・サイドネックフレクション', subtext: '' },
      { name: 'クランチ', subtext: '' },
      { name: 'リバースクランチ', subtext: '' },
    ],
  },
  {
    type: '尻',
    menuNames: [
      { name: 'バックキック', subtext: '' },
      { name: 'ヒップスラスト', subtext: '' },
      { name: 'フロントランジ', subtext: '' },
      { name: 'サイドランジ', subtext: '' },
      { name: 'バックランジ', subtext: '' },
      { name: 'スプリットスクワット', subtext: '' },
      { name: 'ステップアップ', subtext: '' },
      { name: '片脚ヒップスラスト', subtext: '' },
      { name: 'ブルガリアンスクワット', subtext: '' },
      { name: '片脚デッドリフト', subtext: '' },
      { name: 'ブルガリアンスクワット・ジャンプ', subtext: '' },
      { name: 'マニュアルレジスタンス・ブルガリアンスクワット', subtext: '' },
      { name: 'マニュアルレジスタンス・デッドリフト（両手）', subtext: '' },
      { name: 'サイドレッグレイズ', subtext: '' },
      { name: 'サイドヒップリフト', subtext: '' },
      { name: 'マニュアルレジスタンス・デッドリフト（片手）', subtext: '' },
      { name: 'マニュアルレジスタンス・サイドレッグレイズ', subtext: '' },
      { name: 'マニュアルレジスタンス・サイドヒップリフト', subtext: '' },
    ],
  },
  {
    type: '腹',
    menuNames: [
      { name: 'ニートゥーチェスト', subtext: '' },
      { name: 'V シット', subtext: '' },
      { name: 'トータッチ', subtext: '' },
      { name: 'シットアップ', subtext: '' },
      { name: 'L シート', subtext: '' },
      { name: '一文字プッシュアップ', subtext: '' },
      { name: 'ドラゴンフラッグ', subtext: '' },
      { name: 'サイドクランチ', subtext: '' },
      { name: 'トランクツイスト', subtext: '' },
      { name: 'ツイストクランチ', subtext: '' },
      { name: 'ウインドシールドワイパー（床）', subtext: '' },
      { name: ' ウインドシールドワイパー（柱）', subtext: '' },
    ],
  },
  {
    type: '腰',
    menuNames: [
      { name: 'プローンヒップ・フレクション', subtext: '' },
      { name: 'リバース・ブルガリアンスクワット', subtext: '' },
      { name: '片脚シットアップ', subtext: '' },
      { name: 'マニュアルレジスタンス・ヒップフレクション', subtext: '' },
    ],
  },
  {
    type: '脚',
    menuNames: [
      { name: 'スクワット', subtext: '' },
      { name: 'スケータースクワット', subtext: '' },
      { name: 'シシースクワット', subtext: '' },
      { name: 'ピストルスクワット', subtext: '' },
      { name: 'マニュアルレジスタンス・シシースクワット', subtext: '' },
      { name: 'マニュアルレジスタンス・レッグエクステンション', subtext: '' },
      { name: 'ワイドスタンス・スクワット', subtext: '' },
      { name: 'サイドライイング・アダクション', subtext: '' },
      { name: 'マニュアルレジスタンス・アダクション', subtext: '' },
      { name: 'スパインヒップリフト', subtext: '' },
      { name: 'スパインレッグカール', subtext: '' },
      { name: 'グル―トハムレイズ', subtext: '' },
      { name: 'マニュアルレジスタンス・レッグカール①', subtext: '' },
      { name: 'マニュアルレジスタンス・レッグカール②', subtext: '' },
      { name: '片脚カーフレイズ', subtext: '' },
      { name: 'ドンキー片脚カーフレイズ', subtext: '' },
      { name: 'ドンキーカーフレイズ（荷重）', subtext: '' },
      { name: 'マニュアルレジスタンス・トーレイズ', subtext: '' },
    ],
  },
  {
    type: 'ダイナミック',
    menuNames: [
      { name: 'プッシュアップジャンプ', subtext: '' },
      { name: 'スーパーマンジャンプ', subtext: '' },
      { name: 'スクワットジャンプ', subtext: '' },
      { name: 'フライングスプリット', subtext: '' },
      { name: 'ブルガリアン・スクワットジャンプ', subtext: '' },
      { name: '連続サイドジャンプ', subtext: '' },
      { name: 'バウンスジャンプ', subtext: '' },
      { name: '片脚連続ジャンプ', subtext: '' },
    ],
  },
];
export const hiit = [
  {
    type: '全身',
    menuNames: [{ name: 'バービー', subtext: '' }],
  },
];
