export const training = [
  {
    type: '胸',
    menuNames: [
      { name: 'プッシュアップ', subtext: '腕立て伏せです' },
      { name: 'ヒンドゥープッシュアップ', subtext: '尻を上げた後、腰の横まで前方移動する腕立て伏せです' },
      { name: 'リバースプッシュアップ', subtext: '背面の腕立て伏せです' },
      { name: 'ナロープッシュアップ', subtext: '両手の幅を狭めた腕立て伏せです' },
      { name: 'ワイドプッシュアップ', subtext: '両手の幅を広げた腕立て伏せです' },
      { name: 'オルタネートプッシュアップ', subtext: '手の位置を左右非対称にして行う腕立て伏せです' },
      { name: 'クロスプッシュアップ', subtext: '膝を立て、腕を交差して行う腕立て伏せです' },
      { name: '片手プッシュアップ', subtext: '片手を背中につけ、もう一方のみで行う腕立て伏せです' },
      { name: 'トライアングルプッシュアップ', subtext: '親指と人差し指で三角形を作った状態で行う腕立て伏せです' },
    ],
  },
  {
    type: '肩・腕',
    menuNames: [
      { name: '壁プッシュアップ', subtext: '壁に手を伸ばした上で足を壁から離し、両手で壁を押します' },
      { name: 'パイクプッシュアップ', subtext: '両手両足を床につけ、お尻を上に突き出したまま腕立て伏せをします' },
      { name: 'パイクプッシュアップ', subtext: '手を伸ばした腕立て伏せの姿勢から、お尻を上に突き出します' },
      { name: 'プッシュバックプッシュアップ', subtext: '腕立て伏せの下げた状態から、お尻を後ろに突き出します' },
      { name: 'サジタルプッシュアップ', subtext: '胸の真下に手をつき、ひじを後方に折りたたむように行う腕立て伏せです' },
      { name: '逆立ちプレス', subtext: '壁にうつ伏せ倒立の状態で行う腕立て伏せです' },
      { name: 'ハンドスタンドプッシュアップ', subtext: '壁倒立の状態で行う腕立て伏せです' },
      { name: 'ショルダーサイドシットアップ', subtext: '床で横向きの体勢から、肩を使って起き上がります' },
      { name: 'リバースハンドプッシュアップ', subtext: '体の外向きに手をつけ、肘を後ろに引いて行う腕立て伏せです' },
      { name: 'エルボー&エクステンション', subtext: '四つん這いの状態で、上腕を使って肘を上げ下げします' },
      { name: '壁ダイヤモンドプッシュアップ', subtext: '壁に手をダイヤモンドの形において行う腕立て伏せです' },
      { name: 'ダイヤモンドプッシュアップ', subtext: '手をダイヤモンドの形において行う腕立て伏せです' },
    ],
  },
  {
    type: '上背',
    menuNames: [
      { name: 'テーブル・エルボープルアップ', subtext: '' },
      {
        name: 'テーブル・インバーテッドローイング（アンダーグリップ）',
        subtext: '',
      },
      { name: 'テーブル・インバーテッドローイング（オーバーグリップ）', subtext: '' },
      { name: 'シュラッグ', subtext: '' },
      {
        name: 'マニュアルレジスタンス・ワンハンドローイング（ベントオーバー）',
      },
      {
        name: 'マニュアルレジスタンス・ワンハンドローイング（アップライト）',
        subtext: '',
      },
    ],
  },
  {
    type: '首',
    menuNames: [
      { name: 'ネックフレクション', subtext: '' },
      { name: 'サイドネックフレクション', subtext: '' },
      { name: 'フロントブリッジフレクション', subtext: '' },
      { name: 'フロントブリッジツイスト', subtext: '' },
      { name: 'バックブリッジフレクション', subtext: '' },
      { name: 'セルフレジスタンス・サイドネックフレクション', subtext: '' },
      { name: 'セルフレジスタンス・ネックフレクション①', subtext: '' },
      { name: 'セルフレジスタンス・ネックフレクション②', subtext: '' },
      { name: 'マニュアルレジスタンス・ネックフレクション', subtext: '' },
      { name: 'マニュアルレジスタンス・サイドネックフレクション', subtext: '' },
      { name: 'クランチ', subtext: '' },
      { name: 'リバースクランチ', subtext: '' },
    ],
  },
  {
    type: '尻',
    menuNames: [
      { name: 'バックキック', subtext: '' },
      { name: 'ヒップスラスト', subtext: '' },
      { name: 'フロントランジ', subtext: '' },
      { name: 'サイドランジ', subtext: '' },
      { name: 'バックランジ', subtext: '' },
      { name: 'スプリットスクワット', subtext: '' },
      { name: 'ステップアップ', subtext: '' },
      { name: '片脚ヒップスラスト', subtext: '' },
      { name: 'ブルガリアンスクワット', subtext: '' },
      { name: '片脚デッドリフト', subtext: '' },
      { name: 'ブルガリアンスクワット・ジャンプ', subtext: '' },
      { name: 'マニュアルレジスタンス・ブルガリアンスクワット', subtext: '' },
      { name: 'マニュアルレジスタンス・デッドリフト（両手）', subtext: '' },
      { name: 'サイドレッグレイズ', subtext: '' },
      { name: 'サイドヒップリフト', subtext: '' },
      { name: 'マニュアルレジスタンス・デッドリフト（片手）', subtext: '' },
      { name: 'マニュアルレジスタンス・サイドレッグレイズ', subtext: '' },
      { name: 'マニュアルレジスタンス・サイドヒップリフト', subtext: '' },
    ],
  },
  {
    type: '腹',
    menuNames: [
      { name: 'ニートゥーチェスト', subtext: '' },
      { name: 'V シット', subtext: '' },
      { name: 'トータッチ', subtext: '' },
      { name: 'シットアップ', subtext: '' },
      { name: 'L シート', subtext: '' },
      { name: '一文字プッシュアップ', subtext: '' },
      { name: 'ドラゴンフラッグ', subtext: '' },
      { name: 'サイドクランチ', subtext: '' },
      { name: 'トランクツイスト', subtext: '' },
      { name: 'ツイストクランチ', subtext: '' },
      { name: 'ウインドシールドワイパー（床）', subtext: '' },
      { name: ' ウインドシールドワイパー（柱）', subtext: '' },
    ],
  },
  {
    type: '腰',
    menuNames: [
      { name: 'プローンヒップ・フレクション', subtext: '' },
      { name: 'リバース・ブルガリアンスクワット', subtext: '' },
      { name: '片脚シットアップ', subtext: '' },
      { name: 'マニュアルレジスタンス・ヒップフレクション', subtext: '' },
    ],
  },
  {
    type: '脚',
    menuNames: [
      { name: 'スクワット', subtext: '' },
      { name: 'スケータースクワット', subtext: '' },
      { name: 'シシースクワット', subtext: '' },
      { name: 'ピストルスクワット', subtext: '' },
      { name: 'マニュアルレジスタンス・シシースクワット', subtext: '' },
      { name: 'マニュアルレジスタンス・レッグエクステンション', subtext: '' },
      { name: 'ワイドスタンス・スクワット', subtext: '' },
      { name: 'サイドライイング・アダクション', subtext: '' },
      { name: 'マニュアルレジスタンス・アダクション', subtext: '' },
      { name: 'スパインヒップリフト', subtext: '' },
      { name: 'スパインレッグカール', subtext: '' },
      { name: 'グル―トハムレイズ', subtext: '' },
      { name: 'マニュアルレジスタンス・レッグカール①', subtext: '' },
      { name: 'マニュアルレジスタンス・レッグカール②', subtext: '' },
      { name: '片脚カーフレイズ', subtext: '' },
      { name: 'ドンキー片脚カーフレイズ', subtext: '' },
      { name: 'ドンキーカーフレイズ（荷重）', subtext: '' },
      { name: 'マニュアルレジスタンス・トーレイズ', subtext: '' },
    ],
  },
  {
    type: 'ダイナミック',
    menuNames: [
      { name: 'プッシュアップジャンプ', subtext: '' },
      { name: 'スーパーマンジャンプ', subtext: '' },
      { name: 'スクワットジャンプ', subtext: '' },
      { name: 'フライングスプリット', subtext: '' },
      { name: 'ブルガリアン・スクワットジャンプ', subtext: '' },
      { name: '連続サイドジャンプ', subtext: '' },
      { name: 'バウンスジャンプ', subtext: '' },
      { name: '片脚連続ジャンプ', subtext: '' },
    ],
  },
];
export const hiit = [
  {
    type: '全身',
    menuNames: [{ name: 'バービー', subtext: '' }],
  },
];
